export const CREATE_PRIVATE_REQUEST = 'CREATE_PRIVATE_REQUEST'
export const CREATE_PRIVATE_SUCCESS = 'CREATE_PRIVATE_SUCCESS'
export const CREATE_PRIVATE_FAIL = 'CREATE_PRIVATE_FAIL'
export const CREATE_PRIVATE_RESET = 'CREATE_PRIVATE_RESET'

export const PRIVATE_MESSAGE_REQUEST = 'PRIVATE_MESSAGE_REQUEST'
export const PRIVATE_MESSAGE_SUCCESS = 'PRIVATE_MESSAGE_SUCCESS'
export const PRIVATE_MESSAGE_FAIL = 'PRIVATE_MESSAGE_FAIL'
export const PRIVATE_MESSAGE_RESET = 'PRIVATE_MESSAGE_RESET'
