export const CREATE_PRIVATE_REQUEST = 'CREATE_PRIVATE_REQUEST'
export const CREATE_PRIVATE_SUCCESS = 'CREATE_PRIVATE_SUCCESS'
export const CREATE_PRIVATE_FAIL = 'CREATE_PRIVATE_FAIL'
export const CREATE_PRIVATE_RESET = 'CREATE_PRIVATE_RESET'
