export const CREATE_PRIVATE_REQUEST = 'CREATE_PRIVATE_REQUEST'
export const CREATE_PRIVATE_SUCCESS = 'CREATE_PRIVATE_SUCCESS'
export const CREATE_PRIVATE_FAIL = 'CREATE_PRIVATE_FAIL'
export const CREATE_PRIVATE_RESET = 'CREATE_PRIVATE_RESET'

export const PRIVATE_MESSAGE_REQUEST = 'PRIVATE_MESSAGE_REQUEST'
export const PRIVATE_MESSAGE_SUCCESS = 'PRIVATE_MESSAGE_SUCCESS'
export const PRIVATE_MESSAGE_FAIL = 'PRIVATE_MESSAGE_FAIL'
export const PRIVATE_MESSAGE_RESET = 'PRIVATE_MESSAGE_RESET'

export const CREATE_PUBLIC_REQUEST = 'CREATE_PUBLIC_REQUEST'
export const CREATE_PUBLIC_SUCCESS = 'CREATE_PUBLIC_SUCCESS'
export const CREATE_PUBLIC_FAIL = 'CREATE_PUBLIC_FAIL'
export const CREATE_PUBLIC_RESET = 'CREATE_PUBLIC_RESET'

export const PUBLIC_MESSAGE_REQUEST = 'PUBLIC_MESSAGE_REQUEST'
export const PUBLIC_MESSAGE_SUCCESS = 'PUBLIC_MESSAGE_SUCCESS'
export const PUBLIC_MESSAGE_FAIL = 'PUBLIC_MESSAGE_FAIL'
export const PUBLIC_MESSAGE_RESET = 'PUBLIC_MESSAGE_RESET'
