export const SEND_TEXT_REQUEST = 'SEND_TEXT_REQUEST'
export const SEND_TEXT_SUCCESS = 'SEND_TEXT_SUCCESS'
export const SEND_TEXT_FAIL = 'SEND_TEXT_FAIL'
export const SEND_TEXT_RESET = 'SEND_TEXT_RESET'

export const SET_TO_READ_REQUEST = 'SET_TO_READ_REQUEST'
export const SET_TO_READ_SUCCESS = 'SET_TO_READ_SUCCESS'
export const SET_TO_READ_FAIL = 'SET_TO_READ_FAIL'
export const SET_TO_READ_RESET = 'SET_TO_READ_RESET'
