export const SEND_TEXT_REQUEST = 'SEND_TEXT_REQUEST'
export const SEND_TEXT_SUCCESS = 'SEND_TEXT_SUCCESS'
export const SEND_TEXT_FAIL = 'SEND_TEXT_FAIL'
export const SEND_TEXT_RESET = 'SEND_TEXT_RESET'
