export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

export const ADD_CONTACT_REQUEST = 'ADD_CONTACT_REQUEST'
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS'
export const ADD_CONTACT_FAIL = 'ADD_CONTACT_FAIL'
export const ADD_CONTACT_RESET = 'ADD_CONTACT_RESET'

export const SEARCH_REQUEST = 'SEARCH_REQUEST'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAIL = 'SEARCH_FAIL'
export const SEARCH_RESET = 'SEARCH_RESET'

export const ACCEPT_REQUEST = 'ACCEPT_REQUEST'
export const ACCEPT_SUCCESS = 'ACCEPT_SUCCESS'
export const ACCEPT_FAIL = 'ACCEPT_FAIL'
export const ACCEPT_RESET = 'ACCEPT_RESET'

export const DETAILS_REQUEST = 'DETAILS_REQUEST'
export const DETAILS_SUCCESS = 'DETAILS_SUCCESS'
export const DETAILS_FAIL = 'DETAILS_FAIL'
export const DETAILS_RESET = 'DETAILS_RESET'
