export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

export const ADD_CONTACT_REQUEST = 'ADD_CONTACT_REQUEST'
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS'
export const ADD_CONTACT_FAIL = 'ADD_CONTACT_FAIL'
export const ADD_CONTACT_RESET = 'ADD_CONTACT_RESET'

export const SEARCH_REQUEST = 'SEARCH_REQUEST'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAIL = 'SEARCH_FAIL'
export const SEARCH_RESET = 'SEARCH_RESET'

export const ACCEPT_REQUEST = 'ACCEPT_REQUEST'
export const ACCEPT_SUCCESS = 'ACCEPT_SUCCESS'
export const ACCEPT_FAIL = 'ACCEPT_FAIL'
export const ACCEPT_RESET = 'ACCEPT_RESET'

export const DETAILS_REQUEST = 'DETAILS_REQUEST'
export const DETAILS_SUCCESS = 'DETAILS_SUCCESS'
export const DETAILS_FAIL = 'DETAILS_FAIL'
export const DETAILS_RESET = 'DETAILS_RESET'

export const USER_SEARCH_REQUEST = 'USER_SEARCH_REQUEST'
export const USER_SEARCH_SUCCESS = 'USER_SEARCH_SUCCESS'
export const USER_SEARCH_FAIL = 'USER_SEARCH_FAIL'
export const USER_SEARCH_RESET = 'USER_SEARCH_RESET'

export const INVITE_PUBLIC_REQUEST = 'INVITE_PUBLIC_REQUEST'
export const INVITE_PUBLIC_SUCCESS = 'INVITE_PUBLIC_SUCCESS'
export const INVITE_PUBLIC_FAIL = 'INVITE_PUBLIC_FAIL'
export const INVITE_PUBLIC_RESET = 'INVITE_PUBLIC_RESET'

export const DELETE_REQUEST = 'DELETE_REQUEST'
export const DELETE_SUCCESS = 'DELETE_SUCCESS'
export const DELETE_FAIL = 'DELETE_FAIL'
export const DELETE_RESET = 'DELETE_RESET'

export const UPATE_PROFILE_REQUEST = 'UPATE_PROFILE_REQUEST'
export const UPATE_PROFILE_SUCCESS = 'UPATE_PROFILE_SUCCESS'
export const UPATE_PROFILE_FAIL = 'UPATE_PROFILE_FAIL'
export const UPATE_PROFILE_RESET = 'UPATE_PROFILE_RESET'

export const SEARCH_MOBILE_REQUEST = 'SEARCH_MOBILE_REQUEST'
export const SEARCH_MOBILE_SUCCESS = 'SEARCH_MOBILE_SUCCESS'
export const SEARCH_MOBILE_FAIL = 'SEARCH_MOBILE_FAIL'
export const SEARCH_MOBILE_RESET = 'SEARCH_MOBILE_RESET'

export const GOOGLE_FB_LOGIN_REQUEST = 'GOOGLE_FB_LOGIN_REQUEST'
export const GOOGLE_FB_LOGIN_SUCCESS = 'GOOGLE_FB_LOGIN_SUCCESS'
export const GOOGLE_FB_LOGIN_FAIL = 'GOOGLE_FB_LOGIN_FAIL'
export const GOOGLE_FB_LOGIN_RESET = 'GOOGLE_FB_LOGIN_RESET'
